export default {
    status: '',
    token: localStorage.getItem("token") || "",
    user: {},
    users: [],
    errorMessage: "",
    snails: [],
    snailsForGroup: [],
    snuskas: [],
    measuresForSnail: [],
    taxonomies: [],
    taxonomiesTreeView: [],
    boxes: [],
    groups: [],
    groupsForBox:[],
    events: [],
    eventTypes: [],
    eventsForBox: [],
    eventsForSnail: [],
    eventsForGroup: [],
    eventsForSnuska: [],
    files: [],

}