export default {
    status: '',
    token: localStorage.getItem("token") || "",
    activeBox: Number,
    user: {},
    errorMessage: "",
    snails: [],
    snailsForGroup: [],
    snuskas: [],
    measuresForSnail: [],
    taxonomies: [],
    boxes: [],
    groups: [],
    groupsForBox:[],
    events: [],
    eventsForBox: [],
    eventsForSnail: [],
    eventsForGroup: [],
    eventsForSnuska: [],

}